src/core/urls.py
from django.urls import path
from django.shortcuts import redirect
from django.contrib.sitemaps.views import sitemap
from django.utils.translation import gettext_lazy as _
from django.conf.urls import handler404
from . sitemaps import SITEMAPS
from . import views

app_name = 'core'

urlpatterns = [
    path('messages/', views.MessagesTemplateView.as_view(), name='messages'),
    # FAVICONS
    path('favicon.ico', lambda request: redirect('/static/core/favicons/favicon.ico')),
    path('android-chrome-512x512.png', lambda request: redirect('/static/core/favicons/android-chrome-512x512.png')),
    path('android-chrome-192x192.png', lambda request: redirect('/static/core/favicons/android-chrome-192x192.png')),
    path('favicon-32x32.png', lambda request: redirect('/static/core/favicons/favicon-32x32.png')),
    path('favicon-16x16.png', lambda request: redirect('/static/core/favicons/favicon-16x16.png')),
    path('site.webmanifest', lambda request: redirect('/static/core/favicons/site.webmanifest')),
    # SEO
    path('sitemap.xml', sitemap,{'sitemaps': SITEMAPS}, name='django.contrib.sitemaps.views.sitemap'),
]

src/telegram/urls.py
from django.urls import path, re_path

from . import views

app_name = 'telegram'

urlpatterns = [
    path('settings', view=views.SettingsView.as_view(), name='settings'),
    path('webhook', view=views.WebhookView.as_view(), name='webhook'),
    path('get-file/<int:id>/',view=views.GetFileView.as_view(), name='get-file'),
    re_path(r'^audio-player/(?P<ids_str>([0-9]+-)*[0-9]+)/$', view=views.AudioPlayerView.as_view(), name='audio-player'),
    re_path(
        r'^download/multiple-audio/(?P<ids_str>([0-9]+-)*[0-9]+)/$',
        view=views.MultipleAudioDonwloadView.as_view(),
        name='multiple-audio-download'
    ),
]

src/telegram/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from django.core.exceptions import SuspiciousOperation
from .retrived_data import RetrivedData, ChatType

class TelegramForm(forms.Form):
    telegram_data = forms.JSONField()


    def clean_telegram_data(self):
        return self.cleaned_data['telegram_data']

    def get_retrived_data(self) -> RetrivedData:
        telegram_data = self.cleaned_data['telegram_data']
        if 'message' in telegram_data:
            return self._retrive_message_data()
        
        if 'edited_message' in telegram_data:
            return self._retrive_edited_message_data()
        
        if 'my_chat_member' in telegram_data:
            return self._retrive_my_chat_member_data()

        raise SuspiciousOperation(f"Telegram data can not be processed: {telegram_data}")

    def _retrive_message_data(self):
        telegram_data = self.cleaned_data['telegram_data']
        from_data = telegram_data['message']['from']

        return RetrivedData(
            telegram_id=from_data['id'],
            update_id=telegram_data['update_id'],
            username=from_data['username'],
            first_name=from_data['first_name'],
            last_name=from_data['last_name'],
            is_bot=from_data['is_bot'],
            chat_type=ChatType.PRIVATE,
            message_id=telegram_data['message']['message_id'],
            message=telegram_data['message']['text']
        )
    

    def _retrive_edited_message_data(self) -> dict:
        telegram_data = self.cleaned_data['telegram_data']
        from_data = telegram_data['edited_message']['from']

        return RetrivedData(
            telegram_id=from_data['id'],
            update_id=telegram_data['update_id'],
            username=from_data['username'],
            first_name=from_data['first_name'],
            last_name=from_data['last_name'],
            is_bot=from_data['is_bot'],
            chat_type=ChatType.PRIVATE,
            message_id=telegram_data['edited_message']['message_id'],
            message=telegram_data['edited_message']['text']
        )
    

src/telegram/views.py
import logging, json
from io import BytesIO
from zipfile import ZipFile

import requests
from django.conf import settings
from django.http import Http404, HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404
from django.contrib.sites.shortcuts import get_current_site
from django.urls import reverse
from django.views.generic import TemplateView, View
from django.utils.translation import gettext_lazy as _
from django.views.decorators.csrf import csrf_exempt
from django.core.exceptions import SuspiciousOperation

from .retrived_data import RetrivedData
from .commands import command_manager
from . import forms
from .models import TelegramYoutubeDownload, TelegramChatMessage



class SettingsView(TemplateView):
    template_name = 'telegram/settings.html'
    http_method_names = ['get', 'post']

    def dispatch(self, request, *args, **kwargs):
        if not self.has_permission():
            raise Http404()
        
        return super().dispatch(request, *args, **kwargs)  
    

    def has_permission(self) -> bool:
        return self.request.user.is_superuser  
    

    def get_context_data(self, **kwargs) -> dict:
        context = super().get_context_data(**kwargs)
        context['telegram'] = {
            'settings': self._telagram_settings_request(),
            'delete': self._delete_url(),
            'setup': self._setup_url()
        }
        return context
    
    def _setup_url(self) -> str:
        webhook_url = "https://{current_site}{webhook}".format(
            current_site = str(get_current_site(self.request)),
            webhook = reverse('telegram:webhook')
        )

        return "{telegram}{token}/setWebhook?url={webhook_url}&secret_token={secret_token}".format(
            telegram = settings.TELEGRAM_BOT_API_URL,
            token = settings.TELEGRAM_BOT_TOKEN,
            webhook_url = webhook_url,
            secret_token = settings.TELEGRAM_BOT_SECRET
        )
    
    def _delete_url(self) -> str:
        return '{telegram}{token}/deleteWebhook'.format(
            telegram = settings.TELEGRAM_BOT_API_URL,
            token = settings.TELEGRAM_BOT_TOKEN
        )


    def  _telagram_settings_request(self) -> dict:
        url = '{telegram}{token}/getWebhookInfo'.format(
            telegram = settings.TELEGRAM_BOT_API_URL,
            token = settings.TELEGRAM_BOT_TOKEN
        )

        result = requests.get(url).json()['result']
        return json.dumps(result, sort_keys=True, indent=4, ensure_ascii=False)



class WebhookView(View):
    http_method_names = ['post',]

    ERROR_MESSAGES = {
        'bot': _("We don't process commands from bots"),
        'blocked': _("Your account was blocked, talk to the support team to find out more"),
        'invalid_command': _("This command is not valid"),
    }

    @csrf_exempt
    def dispatch(self, request, *args, **kwargs):
        if not self.has_permission():
            raise SuspiciousOperation("Invalid secret key in telegram webhook")

        return super().dispatch(request, *args, **kwargs)
    
    def has_permission(self) -> bool:
        secret_token = self.request.headers.get('X-Telegram-Bot-Api-Secret-Token', None)
        if secret_token != settings.TELEGRAM_BOT_SECRET:
            return False
        
        return True
    
    def post(self, request) -> JsonResponse:
        telegram_form = forms.TelegramForm({'telegram_data': request.body})
        
        if not telegram_form.is_valid():
            raise SuspiciousOperation(f"Invalid telegram webhook form. Errors: {telegram_form.errors}")
        
        retrived_data: RetrivedData = telegram_form.get_retrived_data()

        if retrived_data.is_already_responded():
            logging.debug('Already responded')
            return JsonResponse({})
        
        if not retrived_data.is_allowed_chat_type():
            return JsonResponse({
                'method': 'leaveChat',
                'chat_id': retrived_data.telegram_id
            })
        
        if retrived_data.telegram_account.is_bot:
            return JsonResponse({
                'method': 'sendMessage',
                'text': str(self.ERROR_MESSAGES['bot']),
                'chat_id': retrived_data.telegram_id,
                'reply_to_message_id': retrived_data.message_id,
            })
        
        if retrived_data.telegram_account.is_blocked:
            return JsonResponse({
                'method': 'sendMessage',
                'text': str(self.ERROR_MESSAGES['blocked']),
                'chat_id': retrived_data.telegram_id,
                'reply_to_message_id': retrived_data.message_id,
            })
        
        if not command_manager.is_command_valid(retrived_data.command):
            return JsonResponse({
                'method': 'sendMessage',
                'text':  self.ERROR_MESSAGES['invalid_command'],
                'chat_id': retrived_data.telegram_id,
                'reply_to_message_id': retrived_data.message_id,
            })
        
        telegram_chat_message = TelegramChatMessage.objects.create(
            TelegramAccount_telegram_id = retrived_data.telegram_account,
            update_id = retrived_data.update_id,
            message_id = retrived_data.message_id,
            message = retrived_data.message,
            request_data = telegram_form.cleaned_data['telegram_data']
        )

        command_manager.execute(telegram_chat_message)

        return JsonResponse({})
    

class AudioPlayerView(TemplateView):
    template_name = 'telegram/player.html'
    http_method_names = ['get']
    
       
    def get(self, request, ids_str: str, *args, **kwargs):
        self.additional_context = {
            'youtube_downloads': self.get_youtube_downloads(ids_str),
            'ids_str': ids_str
        }

        return super().get(request, id, *args, **kwargs)
    

    def get_context_data(self, *args, **kwargs) -> dict:
        context = super().get_context_data(**kwargs)
        context.update(self.additional_context)
        return context
    
    def get_youtube_downloads(self, ids_str: str) -> list:
        items = ids_str.split('-')
        ids = [int(x) for x in items]

        TelegramYoutubeDownload.remove_old_youtube_downloads()

        youtube_downloads = TelegramYoutubeDownload.objects.values(
            'id', 'title'
        ).filter(id__in=ids, content_type=0) # 'audio/mpeg'

        return list(youtube_downloads)


class GetFileView(View):
    http_method_names = ['get']
        
    def get(self, request, id: int, *args, **kwargs):
        youtube_download = get_object_or_404(TelegramYoutubeDownload, id=id)
        content_type = youtube_download.get_content_type_display()

        with open(youtube_download.file_path, 'rb') as f:
           file_data = f.read()

        response = HttpResponse(file_data, content_type=content_type)

        # Support for partial requests from the client for file downloads
        response['Accept-Ranges'] = 'bytes'

        if content_type == 'audio/mpeg':
            response['Content-Disposition'] = f'attachment; filename="{youtube_download.title}.mp3"'

        return response
    

class MultipleAudioDonwloadView(View):
    http_method_names = ['get']


    def get(self, request, ids_str: str, *args, **kwargs):

        youtube_downloads = self.get_youtube_downloads(ids_str)       

        zip_bytes = self.create_zip(youtube_downloads)

        response = HttpResponse(zip_bytes, content_type='application/zip')
        response['Accept-Ranges'] = 'bytes'
        response['Content-Disposition'] = f'attachment; filename="musics.zip"'

        return response
    

    def create_zip(self, youtube_downloads: list) -> bytes:
        with BytesIO() as buffer:
            zip_file = ZipFile(buffer, 'w')
            for item in youtube_downloads:
                zip_file.write(
                    filename=item['file_path'],
                    arcname=f'{item['title']}.mp3'
                )
            zip_file.close()
            buffer.seek(0)
            return buffer.read()
    
    def get_youtube_downloads(self, ids_str: str) -> list:
        items = ids_str.split('-')
        ids = [int(x) for x in items]

        youtube_downloads = TelegramYoutubeDownload.objects.values(
            'file_path', 'title'
        ).filter(id__in=ids, content_type=0) # 'audio/mp3'
        
        if not youtube_downloads:
            raise Http404()

        logging.debug(f'Files to zip ({len(youtube_downloads)}): {youtube_downloads}')
        return list(youtube_downloads)

src/telegram/templates/telegram/player-old.html
{% extends "core/base.html" %}
{% load i18n static %}

<!-- Title -->
{% block title %}{% translate 'Download' %}{% endblock title %}

<!-- Menu -->
{% block menu %}{% endblock menu %}

{% block extra_head %}
    <link href="{% static 'fontawesomefree/css/fontawesome.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/solid.css' %}" rel="stylesheet" type="text/css">
{% endblock extra_head %}

<!-- Content -->
{% block content %}
    <div class="flex flex-col justify-center items-center min-h-screen bg-gradient-to-l from-gray-100 via-blue-50 to-gray-100 p-2">
 
        {% if not youtube_downloads %}
            <div 
                class="max-w-2xl w-full py-4 px-3 shadow border border-white border-opacity-5 rounded-lg bg-white overflow-hidden"
            >
                <p class="text-2xl sm:text-3xl text-center uppercase py-2">
                    {% translate "Youtube download not found"%}
                </p>

                <hr class="w-full">
                
                <img src="{% static 'telegram/_img/player/not_found.jpg' %}">
            </div>
        {% else %}
            <script src="{% static 'telegram/_js/player/audio.js' %}" defer></script>
            <div 
                class="max-w-2xl w-full shadow border border-white border-opacity-5 rounded-lg bg-white overflow-hidden"
            >
                <h1 
                    class="text-center text-xl font-bold px-4 py-6 bg-stone-300 overflow-hidden"
                >
                    {{ youtube_download.title }}
                </h1>

                <div id="player" class="select-none">
                    <audio 
                        preload="metadata"
                        type="audio/mp3"
                        src="{% url 'telegram:download' id=id %}"
                        id="audio"
                    ></audio>

                    <div class="w-full flex flex-row items-center">
                        <button 
                            id="play-pause-button"
                            class="px-2 py-1 w-10 text-center"
                        >
                            <i class="fa-solid fa-play"></i>
                        </button>
    
                        <div id="progress-container" class="w-full h-2.5 bg-gray-200 cursor-pointer rounded-full overflow-hidden">
                            <span id="progress-container__bar" class="table h-full bg-orange-500"></span>
                        </div>

                        <div id="timer" class="flex flex-row flex-nowrap px-2">
                            <span id="timer__current-time" class="whitespace-nowrap">00:00</span>/
                            <span id="timer__total-time" class="whitespace-nowrap">--:--</span>
                        </div>
                    </div>
                </div>
            </div>

            <p class="text-center text-red-700 mt-8">
                {% blocktranslate trimmed %}
                    This is a temporary link, it will be removed on a few days
                {% endblocktranslate %}
            </p>

            <a 
                download
                href="{% url 'telegram:download' id=id %}"
                class="btn btn-primary mx-auto my-4 shadow"
            >   
                <i class="fa-solid fa-download"></i>
                {% translate "Download"%}
            </a>

            <canvas id="my-canvas" width="300" height="20"> </canvas>

        {% endif %}

    </div>
{% endblock content %}

<!-- Footer -->
{% block footer %}{% endblock footer %}

src/telegram/templates/telegram/player.html
{% extends "core/base.html" %}
{% load i18n static %}

<!-- Title -->
{% block title %}{% translate 'Download' %}{% endblock title %}

<!-- Menu -->
{% block menu %}{% endblock menu %}

{% block extra_head %}
    <link href="{% static 'fontawesomefree/css/fontawesome.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/solid.css' %}" rel="stylesheet" type="text/css">
{% endblock extra_head %}

<!-- Content -->
{% block content %}
    <div class="flex flex-col justify-center items-center min-h-screen bg-gradient-to-l from-gray-100 via-blue-50 to-gray-100 p-2">
 
        {% if not youtube_downloads %}
            <div 
                class="max-w-2xl w-full py-4 px-3 shadow border border-white border-opacity-5 rounded-lg bg-white overflow-hidden"
            >
                <p class="text-2xl sm:text-3xl text-center uppercase py-2">
                    {% translate "Downloads not found"%}
                </p>

                <hr class="w-full">
                
                <img src="{% static 'telegram/_img/player/not_found.jpg' %}">
            </div>
        {% else %}
            <script src="{% static 'telegram/_js/player/audio.js' %}" defer></script>

            <p class="text-center text-red-700">
                {% blocktranslate trimmed %}
                    This is a temporary link, it will be removed on a few days
                {% endblocktranslate %}
            </p>

            <div 
                class="max-w-2xl w-full mt-8 shadow border border-white border-opacity-5 rounded-lg bg-white overflow-hidden"
            >
                <div class="relative bg-stone-300">
                    {% if youtube_downloads|length > 1 %}
                    <div class="absolute right-0 px-1 font-bold bg-stone-400 text-stone-800">
                        <span id="audio-number">1</span> / {{ youtube_downloads|length }}
                    </div>
                    {% endif %}
    
                    <h1 
                        id="current-audio-title"
                        class="text-center text-xl font-bold px-4 py-6 overflow-hidden"
                    >
                        {% with youtube_downloads|first as first_download %}
                            {{ first_download.title }}
                        {% endwith %}
                    </h1>
                </div>

                <div id="player" class="select-none">
                    {% for item in youtube_downloads %}
                        <audio 
                            id="audio_{{ item.id }}"
                            title="{{ item.title }}"
                            preload="metadata"
                            type="audio/mp3"
                            src="{% url 'telegram:get-file' id=item.id %}"
                        ></audio>
                    {% endfor %}

                    <div class="w-full flex flex-row items-center">
                        <button
                            id="backward-button"
                            class="px-2 py-1"
                        >
                            <i class="fa-solid fa-backward"></i>
                        </button>

                        <button 
                            id="play-pause-button"
                            class="px-1 py-1 ml-px w-8 text-center"
                        >
                            <i class="fa-solid fa-play"></i>
                        </button>

                        <button
                            id="forward-button"
                            class="px-2 py-1 ml-px mr-1"
                        >
                            <i class="fa-solid fa-forward"></i>
                        </button>
    
                        <div id="progress-container" class="w-full h-2.5 bg-gray-200 cursor-pointer rounded-full overflow-hidden">
                            <span id="progress-container__bar" class="table h-full bg-orange-500"></span>
                        </div>

                        <div id="timer" class="flex flex-row flex-nowrap px-2">
                            <span id="timer__current-time" class="whitespace-nowrap">00:00</span>/
                            <span id="timer__total-time" class="whitespace-nowrap">--:--</span>
                        </div>
                    </div>
                </div>
            </div>
            
            {% if youtube_downloads|length > 1 %}
                <figure class="max-w-2xl w-full mt-8 shadow border border-white border-opacity-5 rounded-lg bg-white overflow-hidden">
                    <figcaption class="text-center text-xl bg-stone-300 text-stone-700 p-2">
                        {% translate 'Music list' %}
                    </figcaption>

                    <ol 
                        id="audio_title_list"
                        class="list-decimal list-inside divide-y"
                    >
                        {% for item in youtube_downloads %}
                            <li
                                audio_element_id="audio_{{ item.id }}"
                                class="cursor-pointer text-lg py-1 px-2 hover:font-bold"
                            >
                                {{ item.title }}
                            </li>
                        {% endfor %}
                    </ol>
                </figure>
            {% endif %}

            
            <!-- TODO download="musics.zip" -->
            <a 
                download
                {% if youtube_downloads|length == 1 %}
                    href="{% url 'telegram:get-file' id=youtube_downloads.0.id %}"
                {% else %}
                    href="{% url 'telegram:multiple-audio-download' ids_str=ids_str %}"
                {% endif %}

                class="btn btn-primary mx-auto my-8 shadow"
            >
                <i class="fa-solid fa-download"></i>
                {% translate 'Download' %}
            </a>

              
        {% endif %}

    </div>
{% endblock content %}

<!-- Footer -->
{% block footer %}{% endblock footer %}

src/telegram/templates/telegram/settings.html
{% extends "core/base.html" %}
{% load i18n static %}

<!-- Title -->
{% block title %}{% translate 'Settings' %}{% endblock title %}

{% block extra_head %}
    <script src="{% static 'telegram/_js/highlight/json.min.js' %}" defer></script>
    <script src="{% static 'telegram/_js/settings.js' %}" defer></script>
{% endblock extra_head %}

<!-- Menu -->
{% block menu %}{% endblock menu %}

<!-- Content -->
{% block content %}
    <div class="min-h-screen p-2 bg-blue-400">
        <button id="back-button" class="btn btn-light ml-auto">
            {% translate "Back" %}
        </button>
    
        <h1 class="text-center text-white text-5xl uppercase mt-4">
            {% translate "Settings" %}
        </h1>
    
        <div class="shadow">
            <pre class="mt-12"><code class="hljs language-json">{{ telegram.settings }}</code></pre>
    
            <div id="setting-buttons" class="flex flex-col sm:flex-row bg-white">
                <button
                    url="{{ telegram.delete }}"
                    class="btn btn-danger shadow m-4"
                >
                    {% translate 'Reset' %}
                </button>

                <button
                    url="{{ telegram.setup }}" 
                    class="btn btn-primary shadow m-4"
                >
                    {% translate 'Setup' %}
                </button>        
            </div>
        </div>
    </div>
{% endblock content %}

<!-- Footer -->
{% block footer %}{% endblock footer %}