src/core/urls.py
from django.urls import path
from django.shortcuts import redirect
from django.contrib.sitemaps.views import sitemap
from django.utils.translation import gettext_lazy as _
from django.conf.urls import handler404
from . sitemaps import SITEMAPS
from . import views

app_name = 'core'

urlpatterns = [
    path('messages/', views.MessagesTemplateView.as_view(), name='messages'),
    # FAVICONS
    path('favicon.ico', lambda request: redirect('/static/core/favicons/favicon.ico')),
    path('android-chrome-512x512.png', lambda request: redirect('/static/core/favicons/android-chrome-512x512.png')),
    path('android-chrome-192x192.png', lambda request: redirect('/static/core/favicons/android-chrome-192x192.png')),
    path('favicon-32x32.png', lambda request: redirect('/static/core/favicons/favicon-32x32.png')),
    path('favicon-16x16.png', lambda request: redirect('/static/core/favicons/favicon-16x16.png')),
    path('site.webmanifest', lambda request: redirect('/static/core/favicons/site.webmanifest')),
    # SEO
    path('sitemap.xml', sitemap,{'sitemaps': SITEMAPS}, name='django.contrib.sitemaps.views.sitemap'),
]

src/users/urls.py
from django.conf import settings
from django.urls import include, path
from django.contrib.auth.views import LogoutView 
from django.views.generic import TemplateView
from django.utils.translation import gettext_lazy as _

from . import views

app_name = 'users'

urlpatterns = [
    path('', TemplateView.as_view(template_name='users/index.html'), name='index'),
    path(_('contact/'), views.ContactFormView.as_view(), name='contact'),
    path(_('about/'), TemplateView.as_view(template_name='users/about.html'), name='about'),
    path(_('my-work/'), views.MyWorkTemplateView.as_view(), name='my-work'),
    path(_('books/'), TemplateView.as_view(template_name='users/books.html'), name='books'),
    path('like-dislike/<int:id>/<str:reply>/<int:is_update>/', views.LikeDislikeView.as_view(), name='my-work'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page=settings.LOGIN_URL), name='logout'),
]

src/users/models.py
from django.db import models
from django.contrib.auth.base_user import BaseUserManager, AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin, Group, Permission
from django.utils import timezone
from django.utils.translation import gettext_lazy as _


class CustomUserManager(BaseUserManager):
    def create_user(self, email, password, **other_fields):
        email = self.normalize_email(email)
        user = self.model(email=email, **other_fields)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, password, **other_fields):
        other_fields.setdefault('is_superuser', True)
        return self.create_user(email, password, **other_fields)

class User(AbstractBaseUser, PermissionsMixin):
    # Os campos password, last_login, is_superuser são criados automaticamente do AbstractBaseUser
    id = models.AutoField(
        auto_created=True,
        primary_key=True,
        verbose_name='ID'
    )

    email = models.EmailField(
        unique=True,
        max_length=100,
        blank=False,
        null=False,
        db_index=True
    )

    objects = CustomUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        managed = True
        db_table = 'user'
        verbose_name = 'usuário'
        verbose_name_plural = 'usuários'

    def __str__(self):
        return self.email

    @property
    def is_staff(self):
        return self.is_superuser


class CustomGroup(Group):
    class Meta:
        db_table = 'users_groups'
        proxy = True
        verbose_name = 'grupo'
        verbose_name_plural = 'grupos'


class CustomPermission(Permission):
    class Meta:
        db_table = 'users_permissions'
        proxy = True
        verbose_name = 'permissão'
        verbose_name_plural = 'permissões'


class LikeDislikeCounter(models.Model):
    id = models.AutoField(
        auto_created=True,
        primary_key=True,
        verbose_name='ID'
    )

    description = models.TextField(
        verbose_name='descrição',
        blank=False,
        null=False,
    )

    qt_likes = models.PositiveBigIntegerField(
        verbose_name='quantidade de likes',
        default=0,
        blank=False,
        null=False
    )

    qt_dislikes = models.PositiveBigIntegerField(
        verbose_name='quantidade de dislikes',
        default=0,
        blank=False,
        null=False
    )

    class Meta:
        managed = True
        db_table = 'like_counter'
        verbose_name = 'contador de like/dislike'
        verbose_name_plural = 'contador de likes/deslikes'

    def __str__(self):
        return self.description

src/users/forms.py
import threading
import logging
from django.contrib.auth import authenticate
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.admin.widgets import FilteredSelectMultiple
from django.utils.translation import gettext_lazy as _
from django.core.mail import send_mail
from django.conf import settings
from django import forms

from .models import CustomGroup

class CustomGroupAdminForm(forms.ModelForm):
    class Meta:
        model = CustomGroup
        fields = '__all__'
        widgets = {
            'permissions': FilteredSelectMultiple(_('Permissions'), is_stacked=False)
        }


class CustomAuthenticationForm(AuthenticationForm):
    error_messages = {
        'invalid_login': _('Email and password incorrect, try again'),
        'invalid_permission': _('This user does not have access permission'),
        'inactive': _('This account has been deactivated'),
    }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)     
        self.fields['username'].widget.attrs.pop('autofocus', None)
        
        for field_name in self.fields:
            self.fields[field_name].widget.attrs['class'] = ' form-input'

            if self.has_error(field_name):
                self.fields[field_name].widget.attrs['class'] += ' invalid-field'
    

    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        if username is not None and password:
            self.user_cache = authenticate(
                self.request, username=username, password=password
            )
            if self.user_cache is None:
                raise self.get_invalid_login_error()
            
            if self.user_cache.is_staff is False:
                raise forms.ValidationError(self.error_messages['invalid_permission'])
            
            self.confirm_login_allowed(self.user_cache)
    

class ContactForm(forms.Form):
    fullname = forms.CharField(
        required=True,
        label=_('Fullname'),
        max_length=50,
    )

    email = forms.EmailField(
        required=True,
        max_length=100,
        label='Email',
    )

    telephone = forms.CharField(
        required=False,
        label=_('Telephone (optional)'),
        max_length=20,
    )

    message = forms.CharField(
        required=True,
        label=_('Message'),
        max_length=800,
        widget=forms.Textarea()
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name in self.fields:
            if field_name in ('fullname', 'email', 'telephone'):
                self.fields[field_name].widget.attrs['class'] = 'form-input'

            if field_name in ('message',):
                self.fields[field_name].widget.attrs['class'] = 'form-textarea'

            if self.has_error(field_name):
                self.fields[field_name].widget.attrs['class'] += ' invalid-field'


    class EmailThread(threading.Thread):
        def __init__(self, subject, html_message, recipient_list, fail_silently=False):
            self.subject = subject
            self.recipient_list = recipient_list
            self.html_message = html_message
            self.fail_silently = fail_silently
            threading.Thread.__init__(self)

        def run(self):
            send_mail(
                subject=self.subject,
                html_message=self.html_message,
                recipient_list=self.recipient_list,
                message=None,
                from_email=None,
                fail_silently=self.fail_silently,
            )


    def sendEmail(self):
        html_message = f'''
            <div>
                <p style='display:block'>Name: {self.cleaned_data['fullname']}</p>
                <p style='display:block'>Email: {self.cleaned_data['email']}</p>
                <p style='display:block'>Telefone: {self.cleaned_data['telephone']}</p>
                <p style='display:block'>Mensagem: {self.cleaned_data['message']}</p>
            </div>
        '''
        logging.info(f'Website Contact: {html_message}')
        self.EmailThread(
            subject='Contact',
            html_message=html_message,
            recipient_list=[settings.EMAIL_SUPPORT],
        ).start()

src/users/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.views import LoginView
from django.urls import reverse, reverse_lazy
from django.views.generic.edit import FormView
from django.http import HttpResponse
from django.views.generic import TemplateView, View
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import get_object_or_404, redirect
from django.utils.translation import gettext_lazy as _

from . import forms, models


class Login(LoginView):
    form_class = forms.CustomAuthenticationForm
    template_name = 'users/login.html'
    
    @csrf_exempt
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)
    
    def get_success_url(self):
        return reverse_lazy('admin:index')
    

class ContactFormView(FormView):
    template_name = 'users/contact.html'
    form_class = forms.ContactForm
    
    def form_valid(self, form) -> HttpResponse:
        form.sendEmail()
        self.request.session[settings.SESSION_REDIRECT_URL] = reverse('users:index')
        messages.success(
            request=self.request, 
            message=_('Message received, I will contact you as soon as possible.')
        )
        return redirect('core:messages')

class MyWorkTemplateView(TemplateView):
    template_name='users/my-work.html'

    def get_context_data(self, **kwargs) -> dict:
        context = super().get_context_data(**kwargs)
        context['like_dislike_1'] = models.LikeDislikeCounter.objects.get(id=1)
        context['like_dislike_2'] = models.LikeDislikeCounter.objects.get(id=2)
        return context
    
class LikeDislikeView(View):
    http_method_names = ['post', 'get']
    
    def get(self, request, id, reply, is_update, *args, **kwargs):
        counter = get_object_or_404(models.LikeDislikeCounter, id=id)
        is_update = True if is_update == 1 else False
        
        if reply == 'like':
            counter.qt_likes += 1
            if is_update:
                counter.qt_dislikes -=1

        if reply == 'dislike':
            counter.qt_dislikes +=1
            if is_update:
                counter.qt_likes -=1

        if reply == 'remove-like':
            counter.qt_likes -=1

        if reply == 'remove-dislike':
            counter.qt_dislikes -=1

        counter.save(update_fields=['qt_likes', 'qt_dislikes']) 
        return HttpResponse('ok')

src/users/templates/users/contact.html
{% extends 'core/base.html' %}
{% load static i18n %}

{% block title %}
    {% translate "Contact"%}
{% endblock %}

{% block meta_description %}{% blocktranslate trimmed %}
        Get in touch using the form sent with your name, email, telephone number (optional) and a message. You can also contact the Clinic on +55 83 3245-8983 or chat via WhatsApp on +55 83 98171-8520. Or, if you prefer, go directly to the Clinic located at: Avenida Euzely Fabrício de Souza, 445, Manaíra, 58038-410, João Pessoa – PB, Brazil.
{% endblocktranslate %}{% endblock %}


{% block extra_head %}
    <link href="{% static 'fontawesomefree/css/fontawesome.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/brands.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/solid.css' %}" rel="stylesheet" type="text/css">
    <script src="{% static 'users/_js/contact.js' %}" defer></script>
{% endblock %}

{% block content %}
    <div class=" min-h-[var(--screen-height)] flex items-center justify-center bg-neutral-100">
        <div 
            class="flex flex-col items-stretch w-11/12 max-w-5xl my-8 rounded-xl shadow border border-gray-200 overflow-hidden lg:flex-row"
        >
            <div class="flex-1 relative z-10 flex flex-col items-center justify-center px-2">
                <img 
                    src="{% static 'users/_img/contact/clinic.webp' %}"
                    alt="{% translate 'Clinic' %}"
                    class="absolute -z-10 h-full w-full object-cover object-center brightness-30"   
                />

                <h2 class="text-white text-4xl mt-10 text-center">
                    {% translate "My office" %}
                </h2>

                <div>
                    <div class="flex flex-row flex-nowrap items-start justify-start m-4 py-2">
                        <i class="fa-solid fa-location-dot mr-4 text-lg mt-1 text-red-600"></i>
                        
                        <div>
                            <h2 class="text-white text-xl">
                                {% translate "Address" %}
                            </h2>
    
                            <p class="text-gray-200/95">
                                Avenida Euzely Fabrício de Souza, 445, Manaíra
                            </p>

                            <p class="text-gray-200/95">
                                João Pessoa – PB
                            </p>

                            <p class="text-gray-200/95">
                                58038-410
                            </p>

                            <a 
                                href="https://maps.app.goo.gl/K39ykK5NKcEgBUoy8"
                                target="_blank"
                                class="btn mx-auto text-white mt-2 hover:bg-white hover:text-black"
                            >
                                <div class="flex justify-center items-center flex-nowrap">
                                    <i class="fa-brands fa-google text-lg mr-3"></i>

                                    <span>
                                        {% translate "View location on map" %}
                                    </span>
                                </div>
                            </a>
                        </div>
                    </div>
                    
                    <a 
                        href="https://api.whatsapp.com/send/?phone=5583981718520"
                        target="_blank"
                        class="table cursor-pointer"
                    >
                        <div class="flex flex-row flex-nowrap items-start justify-start m-4 py-2">
                            <i class="fa-brands fa-whatsapp mr-3 text-3xl text-green-500"></i>
                            
                            <div>
                                <h2 class="text-white text-xl">
                                    WhatsApp
                                </h2>
                                
                                <p class="text-green-500 tracking-wider">+55 83 98171-8520</p>

                                </a>
                            </div>
                        </div>
                    </a>
                    <div
                        id="phone-container"
                        class="flex flex-row items-start justify-start m-4 py-2 cursor-pointer"
                    >
                        <i class="fa-solid fa-phone mr-4 text-lg mt-1.5 text-yellow-500"></i>
                        
                        <div>
                            <h2 class="text-white text-xl">
                                {% translate "Telephone" %}
                            </h2>
                            
                            <p id="phone-container__number" class="text-yellow-500 tracking-wider">
                                +55 83 3245-8983
                            </p>
                            <p id="copied-message" class="w-full text-yellow-300 invisible">
                                <i class="fa-regular fa-copy"></i>
                                {% translate "Copied" %}
                            </p>
                        </div>
                    </div>
                </div>
            </div>

            <form method="post" class="bg-white px-4 sm:px-6 py-12 md:px-14">
                <h1 
                    class="uppercase text-4xl font-title font-bold select-none text-bold text-center bg-clip-text text-transparent bg-gradient-to-r from-blue-400 to-blue-800"
                >
                    {% translate "Get in touch" %}
                </h1>

                <p class="text-center text-gray-400 mb-4">
                    {% translate "Feel free to send me a message" %}
                </p>

                {% csrf_token %}

                {% for error in form.non_field_errors %}
                    {% include "core/components/messages/danger.html" with message=error %}
                {% endfor %}

                {% for field in form %}
                    <label 
                        for="{{ field.id_for_label }}"
                        class="form-label text-gray-700" 
                    >
                        {{ field.label|striptags }}
                    </label>

                    {{ field }}

                    {% if field.errors %}
                        <small class="field-error">{{ field.errors|striptags }}</small> 
                    {% endif %}
                    
                {% endfor %}
                    
        
                <button type="submit" class="btn btn-primary mx-auto mt-6">
                    {% translate "Submit" %}
                </button>
            </form>
        </div>
        
    </div>
{% endblock %}

{% block footer %}{% endblock footer %}

src/users/templates/users/index.html
{% extends 'core/base.html' %}
{% load static i18n %}
{% get_current_language as LANGUAGE_CODE %}

{% block meta_description %}{% blocktranslate trimmed %}
    Wandecleide Lucena Fernandes is a Nurse and Therapist with over 36 years of professional experience who has a PHD in Nursing focused on the treatment of stress, trauma, phobias and anxiety disorders, for adults and the elderly.
{% endblocktranslate %}{% endblock %}

{% block extra_head %}  
    <script src="{% static 'users/_js/index.js' %}" defer></script>
    <script src="{% static 'core/_js/observed.js' %}" defer></script>
{% endblock %}

{% block content %}
    <div 
        id="view-1"
        class="min-h-[var(--screen-height)] relative flex justify-center items-center xl:items-end flex-col overflow-hidden"
    >
        <video
            id="view-1__background-video" autoplay loop muted playsinline preload
            class="absolute top-0 h-full w-full object-cover" style="object-position: 32% 0;"
        >
            <source 
                media="(min-width: 1200px)"
                src="{% static 'users/_video/index/background.mp4' %}"
                type="video/mp4"
            />

            <source 
                src="{% static 'users/_video/index/background_resized.mp4' %}"
                type="video/mp4"
            />

            
            <track 
                kind="descriptions" 
                srclang="en"
                src="{% static 'users/_video/index/en_descriptions.vtt' %}"
            >

            <track 
                kind="captions" 
                srclang="en"
                src="{% static 'users/_video/index/en_captions.vtt' %}"
            >
        </video>

        <div class="bg-black bg-opacity-50 max-w-md w-11/12 m-4 p-4 rounded-md xl:mr-40 xl:-mt-60 relative animate-fadeIn-bottom xl:animate-fadeIn-right">
            <p class="text-center text-white text-shadow text-xl [&>strong]:uppercase [&>strong]:text-blue-400">
                {% blocktranslate trimmed %}
                    Shock, trauma, anxiety disorders and other types of stress can be overcome through <strong>Somatic Experiencing &reg;</strong>
                {% endblocktranslate %}
            </p>
            
            <button id="scroll_button_1" class="btn btn-primary mx-auto mt-4 mb-2 ">
                {% translate "Read more" %}
            </button>

        </div>

    </div>

    <div 
        id="view-2"
        class="min-h-[var(--screen-height)] relative overflow-hidden"
    >
        <h1 class="mt-10">
            <strong class="block text-center text-4xl font-black bg-clip-text text-transparent bg-gradient-to-r from-sky-400 to-teal-800 sm:text-5xl">
                {% translate 'Dr.' %} Wandecleide Fernandes
            </strong>
            <span class="block text-center text-2xl text-gray-500">
                {% translate 'PhD in Nursing' %}
            </span>
        </h1>


        <div class="flex flex-col justify-between items-center w-11/12 max-w-5xl mx-auto mt-12 lg:flex-row">
            <img 
                id="view-2__img"
                src="{% static 'users/_img/index/myself.webp' %}"
                alt="{% translate 'Myself picture' %}"
            />

            <div>
                <div 
                    class="relative max-w-md shadow p-4 border border-gray-200 rounded-md my-6 mx-2 sm:animate-fadeIn-right sm:animation-delay-400 observed"
                >
                    <p class="text-justify">
                        {% blocktranslate trimmed %}
                            I am a Nurse and Therapist, with a PhD in Nursing. I searched for the best courses in Brazil and abroad with the aim of helping my clients to lead a more harmonious and well-being life.
                        {% endblocktranslate %}
                    </p>

                    <a href="{% url 'users:about' %}" class="btn btn-light mx-auto mt-2 relative z-10 w-40">
                        {% translate "About myself" %}
                    </a>
                </div>

                <div 
                    class="relative max-w-md shadow p-4 border border-gray-200 rounded-md my-6 mx-2 sm:animate-fadeIn-right sm:animation-delay-1200 observed"
                >
                    
                    <p class="text-justify">
                        {% blocktranslate trimmed %}
                            My experience is focused on treating stress, trauma, phobias and anxiety disorders, for adults and seniors.
                        {% endblocktranslate %}
                    </p>

                    <a href="{% url 'users:my-work' %}" class="btn btn-light mx-auto mt-2 relative z-10 w-40">
                        {% translate "My work" %}
                    </a>
                
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

{% block footer %}
    {{ block.super }}
{% endblock %}

src/users/templates/users/login.html
{% extends 'core/base.html' %}
{% load static i18n %}

{% block extra_head %}
	<script src="{% static 'core/_js/messages/delete_alert.js' %}" defer></script>
{% endblock %}

{% block menu %}{% endblock menu %}

{% block content %}
	<div class="min-h-screen flex justify-center items-center">
		<form method="post" class="form">
			{% csrf_token %}
	
			{% for error in form.non_field_errors %}
				{% include "core/components/messages/danger.html" with message=error %}
			{% endfor %}

			{% for field in form %}
				<label class="form-label text-gray-700" >
					{{ field.label|striptags }}
				</label>

				{{ field }}

				{% if field.errors %}
					<small class="field-error">{{ field.errors|striptags }}</small> 
				{% endif %}
				
			{% endfor %}

			<button type="submit" class="btn btn-primary table mx-auto mt-4">Entrar</button>
		</form>
	</div>
{% endblock content %}

{% block footer %}{% endblock footer %}